# Generated by Django 3.1.2 on 2020-10-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='title')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='organizer.enterprise', verbose_name='enterprise')),
                ('tags', models.ManyToManyField(blank=True, related_name='post', to='organizer.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'website post',
                'verbose_name_plural': 'website posts',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
                'unique_together': {('slug', 'title')},
            },
        ),
    ]
