# Generated by Django 3.1.2 on 2020-10-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='A label for url config', max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('slug', models.SlugField(help_text='A label for url config', max_length=128, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('founded_date', models.DateTimeField(verbose_name='date founded')),
                ('contact', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('website', models.URLField(max_length=255, verbose_name='website')),
                ('tags', models.ManyToManyField(blank=True, related_name='enterprise', to='organizer.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'ordering': ['name'],
                'get_latest_by': 'founded_date',
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('link', models.URLField(max_length=255, verbose_name='link')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newslink', to='organizer.enterprise', verbose_name='Enterprise')),
            ],
            options={
                'verbose_name': 'news article',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
                'unique_together': {('slug', 'enterprise')},
            },
        ),
    ]
